apiVersion: v1
kind: Service
metadata:
  name: nodejs-login-chat-app
spec:
  selector:
    app: nodejs-login-chat-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort