apiversion: v1
kind: service
metadata:
  name: nodejs-login-chat-app
spec:
  selector:
    app: nodejs-login-chat-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer  