name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v2
      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-login-chat-app:latest .
      - name: push docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-login-chat-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs-login-chat-app:latest
      - name: Remove old container
        run: docker rm -f nodejs-login-chat-app
      - name: Run new container
        run: docker run -d -p 8080:8080 --name nodejs-login-chat-app ${{ secrets.DOCKER_USERNAME }}/nodejs-login-chat-app:latest
      - name: Notify deployment
        run: echo "Deployment successful! The application is now running on port 8080." 

