name: Deploy Node.js App to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-login-chat-app:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-login-chat-app:latest

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest

      - name: Load Docker Image into Minikube
        run: minikube image load ${{ secrets.DOCKER_USERNAME }}/nodejs-login-chat-app:latest

      - name: Validate Kubernetes Manifests
        run: |
          if [ ! -f deployment.yml ]; then
            echo "Error: deployment.yml not found" && exit 1
          fi
          if [ ! -f service.yml ]; then
            echo "Error: service.yml not found" && exit 1
          fi
          kubectl apply --dry-run=client -f deployment.yml
          kubectl apply --dry-run=client -f service.yml

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f deployment.yml
          kubectl apply -f service.yml

      - name: Wait for Deployment to Rollout
        run: kubectl rollout status deployment/nodejs-login-chat-app --timeout=180s

      - name: Wait for Pods to be Ready
        run: |
          echo "Waiting for pods to be ready..."
          kubectl wait --for=condition=ready pod -l app=nodejs-login-chat-app --timeout=360s

      - name: Debug Kubernetes Resources
        run: |
          kubectl get all
          kubectl describe deployment nodejs-login-chat-app
          kubectl logs -l app=nodejs-login-chat-app || echo "No logs found"

      - name: Get App URL
        run: |
          echo "Fetching service URL..."
          sleep 10
          minikube service nodejs-login-chat-app --url || echo "Service not ready yet"

      - name: Notify Deployment Success
        run: echo "✅ Deployment successful! Your app is running in Minikube."
